name: learn-github-actions
on: [push, pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Ref
        run: echo ${{ github.ref }}
      - run: echo ${{ github.sha }}
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Name
        run: echo "name=${GITHUB_REF#refs/}" >> $GITHUB_ENV

      # print branch name
      - name: Get branch name
        run: |
             echo 'The tag name is' ${{ env.name }}
             echo 'Another way? '`${{ github.ref }}#refs/`


