name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build" ]
        include:
     
          - name: "Build"
        
    steps:

      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Brew Install
        run : |
          pwd
          brew install pygobject3 adwaita-icon-theme gtksourceview3 \
                       coreutils autogen ginac cppunit eigen boost \
                       vtk openmpi gmsh jing-trang gcc
          pip3 install numpy matplotlib scipy lxml sympy

      - name: PETSc Install
        run : |
          pwd
          mkdir -p deps
          cd deps
          pwd
          git clone -b v3.14.6 -q https://gitlab.com/petsc/petsc.git
          cd petsc
          python3 ./configure --COPTFLAGS="-O0" \
                              --CXXOPTFLAGS="-O0" \
                              --FOPTFLAGS="-O0" \
                              --with-shared-libraries=1 \
                              --with-openblas=1 \
                              --with-debugging=1 \
                              --download-suitesparse=1 \
                              --download-hypre=1 \
                              --download-ml=1 \
                              --download-parmetis=1 \
                              --download-metis=1 \
                              --download-blacs=1 \
                              --download-scalapack=1 \
                              --download-mumps=1 \
                              --prefix=../../install


      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: configure
          path: deps/petsc/configure.log



