name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build" ]
        include:
     
          - name: "Build"
        
    steps:

      - name: Brew Install
        run : |
          brew install pygobject3 adwaita-icon-theme gtksourceview3 \
                       coreutils autogen ginac cppunit eigen boost \
                       vtk openmpi gmsh jing-trang
          pip3 install numpy matplotlib scipy lxml sympy

      - name: PETSc Install
        run : |
          pwd
          git clone https://bitbucket.org/tferma/petsc.git
          cd petsc
          ./configure --with-shared-libraries=1 \
                      --download-suitesparse=0 \
                      --download-hypre=0 \
                      --download-ml=0 \
                      --download-parmetis=0 \
                      --download-metis=0 \
                      --download-blacs=0 \
                      --download-scalapack=0 \
                      --download-mumps=0 \
                      --with-debugging=1

      - uses: actions/upload-artifact@v2
        with:
          path: petsc/configure.log



