name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build" ]
        include:
     
          - name: "Build"
        
    steps:

      - name: Brew Install
        run : |
          brew install pygobject3 adwaita-icon-theme gtksourceview3 \
                       coreutils autogen ginac cppunit eigen boost \
                       vtk openmpi gmsh jing-trang
          pip3 install numpy matplotlib scipy lxml sympy

      - name: PETSc Install
        run : |
          pwd
          git clone https://bitbucket.org/tferma/petsc.git
          cd petsc
          ./configure --with-clanguage=C++ \
                      --with-shared-libraries=1 \
                      --download-suitesparse=1 \
                      --download-hypre=1 \
                      --download-ml=1 \
                      --download-parmetis=1 \
                      --download-metis=1 \
                      --download-blacs=1 \
                      --download-scalapack=1 \
                      --download-mumps=1 \
                      --with-debugging=0


