name: Build

on: [push]

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        name: [ "Build" ]
        include:
     
          - name: "Build"
        
    steps:

      - name: Brew Install
        run : |
          brew install pygobject3 adwaita-icon-theme gtksourceview3 \
                       coreutils autogen ginac cppunit eigen boost \
                       vtk openmpi gmsh jing-trang
          pip3 install numpy matplotlib scipy lxml sympy

